bl = int(input("Enter block length: "))
bw = int(input("Enter block width: "))
hl = int(input("Enter house length: "))
hw = int(input("Enter house width: "))
print(f"Mowing cost is {((bl*bw)-(hl*hw))*35} baht.")